name: Release afsctool Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: { }

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload afsctool Binaries
    runs-on: macos-11
    strategy:
      matrix:
        targets:
         - 11.7/x86_64-apple-macos10.15
         - 12.5.1/x86_64-apple-macos11
         # No arm64 support currently

    steps:
      - name: Get build machine info
        run: |
          system_profiler SPSoftwareDataType SPHardwareDataType

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          brew install google-sparsehash

      - name: Switch Xcode Version
        run: |
          TARGETS=${{ matrix.targets }}
          sudo xcode-select -s /Applications/Xcode_${TARGETS%/*}.app

      - name: Get Version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#refs/heads/}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        
      - name: Get SDK Version
        id: get_sdk_version
        run: |
          xcrun --show-sdk-version
          echo "SDK_VERSION=$(xcrun --show-sdk-version)" >> $GITHUB_OUTPUT

      - name: Get Target
        id: get_target
        run: |
          TARGETS=${{ matrix.targets }}
          echo "TARGET=${TARGETS#*/}" >> $GITHUB_OUTPUT

      - name: Build Binaries
        run: |
          mkdir build
          cd build
          TARGETS=${{ matrix.targets }}
          cmake -Wno-dev -DCMAKE_CXX_FLAGS="-target ${TARGETS#*/}" ..
          make -j$(sysctl -n hw.ncpu)

      - name: Test Compression
        run: |
          build/afsctool -c -J2 -T LZFSE .github

      - name: Package
        run: |
          cd build
          tar czf afsctool-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_target.outputs.TARGET }}.tar.gz afsctool

      - name: Attach Binaries to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, 'alpha') || contains(steps.get_version.outputs.VERSION, 'beta') }}
          files: |
            build/afsctool-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_target.outputs.TARGET }}.tar.gz
      
      - name: Clean Build Artifacts
        run: |
          cd build
          make clean
