name: Release afsctool Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: { }

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload afsctool Binaries
    runs-on: macos-11
    strategy:
      matrix:
        targets:
         - 11.7/x86_64
         - 12.5.1/x86_64
         # - 13.1/x86_64 Not working
         # No arm64 support currently

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          brew install google-sparsehash

      - name: Get Target
        id: get_target
        run: |
          TARGETS=${{ matrix.targets }}
          echo ::set-output name=XCODE_VERSION::${TARGETS%/*}
          echo ::set-output name=ARCH::${TARGETS#*/}

      - name: Switch Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ steps.get_target.outputs.XCODE_VERSION }}.app
     
      - name: Get Version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#refs/heads/}
          echo ::set-output name=VERSION::${VERSION}
      
      - name: Get SDK Version
        id: get_sdk_version
        run: |
          echo ::set-output name=SDK_VERSION::$(xcrun --show-sdk-version)
    

      - name: Build Binaries
        run: |
          mkdir build
          cd build
          cmake -Wno-dev -DCMAKE_CXX_FLAGS="-arch ${{ steps.get_target.outputs.ARCH }}" ..
          make -j$(sysctl -n hw.ncpu)

      - name: Package
        run: |
          cd build
          tar czf afsctool-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_sdk_version.outputs.SDK_VERSION }}-${{ steps.get_target.outputs.ARCH }}.tar.gz afsctool

      - name: Attach Binaries to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, 'alpha') || contains(steps.get_version.outputs.VERSION, 'beta') }}
          files: |
            build/afsctool-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_sdk_version.outputs.SDK_VERSION }}-${{ steps.get_target.outputs.ARCH }}.tar.gz
      
      - name: Clean Build Artifacts
        run: |
          cd build
          make clean
